apiVersion: v1
kind: Service
metadata:
  name: breast-cancer-classifier-service
spec:
  selector:
    app: breast-cancer-classifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
